### PR TITLE
Fix package deduplication

### LINKED ISSUE #67: Error in ask_user: duplicate row.names
```r
options(bspm.version.check=TRUE)
rdeps <- tools::package_dependencies("units", which="all", reverse=TRUE)[[1]]
install.packages(rdeps, dependencies=TRUE)
```

results in

```
  There are binary versions available but the source versions are later:
Error in data.frame(binary = binvers, source = srcvers, row.names = bins,  : 
  duplicate row.names: classInt, elevatr, EML, eplusr, ggforce, gtfs2gps, gtfstools, gunit, hydraulics, iNZightTools, jpmesh, lwgeom, mapboxapi, meteospain, nhdplusTools, nngeo, pillar, PKNCA, quantities, rmapshaper, rxode2, rxode2et, sf, smoothr, spdep, stars, tealeaves, tidycensus, tmap, tmaptools, vein, wikilake
```

~even if there seems to be no duplicates (?).~ Ah, the names shown __are__ the duplicates. :)

### PR DESCRIPTION
**Pull request by Enchufa2**
Closes #67

### CODE REVIEW

File: tests/r2u.sh [hunk 1]
```diff
@@ -14,3 +16,10 @@ install.r BiocParallel
 echo "TEST: install binary deps + binary from r-universe"
 REPO_URL="https://eddelbuettel.r-universe.dev/bin/linux/$VERSION_CODENAME/${RVER%.*}"
 install2.r -r $REPO_URL RcppKalman
+
+# Tests for default path
+echo "options(bspm.version.check=TRUE)" >> /etc/R/Rprofile.site
+echo "options(install.packages.compile.from.source='never')" >> /etc/R/Rprofile.site
```
Comment (eddelbuettel) [inline tests/r2u.sh:22]: Is that one new?

Comment (Enchufa2) [reply tests/r2u.sh:22]: No, it's the same. But the failure was specific to this code path, so I added this section.
